version: '3'

services:
  frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    environment:
      - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: ghcr.io/shuffle/shuffle-backend:latest
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps:z
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files:z
    env_file: .env
    environment:
      - SHUFFLE_APP_HOTLOAD_FOLDER=/shuffle-apps
      - SHUFFLE_FILE_LOCATION=/shuffle-files
      - SHUFFLE_MEMCACHED=10.15.40.250:11211 # Ini tambahan
    restart: unless-stopped

  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHUFFLE_APP_SDK_TIMEOUT=300 # Ini diubah
      - SHUFFLE_ORBORUS_EXECUTION_CONCURRENCY=5 # Ini diubah
      - ENVIRONMENT_NAME=Shuffle # Ini ubah
      - BASE_URL=http://10.15.40.250:5001 # Ini ubah
      - DOCKER_API_VERSION=1.40 # Ini ubah
      - SHUFFLE_BASE_IMAGE_NAME=frikky # Ini ubah
      - SHUFFLE_BASE_IMAGE_REGISTRY=ghcr.io # Ini ubah
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX="-1.0.0" # Ini ubah
      - CLEANUP=true # Ini ubah
      - SHUFFLE_ORBORUS_EXECUTION_TIMEOUT=600 # Ini ubah
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    hostname: shuffle-opensearch
    container_name: shuffle-opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms8192m -Xmx8192m" # Ini ubah sehingga -Xms dan -Xmx sebesar setengah dari RAM
      - bootstrap.memory_lock=true
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.initial_master_nodes=shuffle-opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=shuffle-cluster
      - node.name=shuffle-opensearch
      - node.store.allow_mmap=false
      - discovery.seed_hosts=shuffle-opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${DB_LOCATION}:/usr/share/opensearch/data:z
    ports:
      - 9200:9200
    networks:
      - shuffle
    restart: unless-stopped

networks:
  shuffle:
    driver: bridge
